### ISSUE TITLE
希望能自定义子目录、支持粘贴直接上传。

### ISSUE THREAD

**Issue by ceeji** [git-patrickliu/QINIU-save-online-images#1]
插件非常好用！提出两个非常有用的需求，如果能实现就极其完美了。

- 支持子目录，方便一个 bucket 有不同用途时不易混淆。
- 提供一个页面，直接 Ctrl+V粘贴，剪切板中图片即可上传到七牛。

第二点，有个扩展实现了新浪微博的图床，名字就是 新浪微博图床，可以搜索参考一下。

如果有这两点，就极其极其方便了！

**Comment by git-patrickliu** [comment]
谢谢，我看一下，近期抽空加上这两个功能：）

**Comment by git-patrickliu** [comment]
@ceeji  ctrl+v粘贴上传图片功能已实现。现已在chrome app store发布中，一小时之后应该就会自动更新了。版本是0.0.6。

**Comment by ceeji** [comment]
谢谢！动作真快！

**Comment by qlynick** [comment]
有些图片地址没有后缀或奇怪的后缀，希望这样的可以强制写后缀就好了
例：http://t10.baidu.com/it/u=1365317415,2169922487&fm=76 像这个网址的图片，保存后下载图片了

**Comment by git-patrickliu** [comment]
@qlynick 不好意思，没理解你这边说的是什么：）能再具体解释一下吗

**Comment by git-patrickliu** [comment]
@ceeji 新目录功能也已开发完毕：）欢迎体验及反馈问题。

**Comment by git-patrickliu** [comment]
@qlynick 我了解你的意思了。我已经做了修改，如果默认无后缀，强制加后缀为jpeg ，虽然可能格式会有点问题，但是至少可以解决你现在的问题：）新版已发布。
