### ISSUE TITLE
如果保存前设置一下名字就好了

### ISSUE THREAD

**Issue by Dev-Wiki** [git-patrickliu/QINIU-save-online-images#3]
现在都是默认随机生成一个名字,如果可选设置名字就好了

**Comment by git-patrickliu** [comment]
嗯。我看看交互上怎么能更方便一些：）

**Comment by Dev-Wiki** [comment]
设置选项里面设置是否需要每次上传设置名称,如果开启当上传之前弹窗填写要保存的文件名称.

**Comment by git-patrickliu** [comment]
已增加，在options里面进行配置。但是点击存的icon，在小弹框里面粘贴是没有填入图片的弹框，因为会冲突。
