### ISSUE TITLE
希望图片能够瘦身，加上  问号imageslimh后缀

### ISSUE THREAD

**Issue by Seifon** [git-patrickliu/QINIU-save-online-images#7]

**Comment by git-patrickliu** [comment]
@Dev-Wiki 嗯，是的 @Seifon 因为这个插件是基于七牛的，所以可以在url后面跟上七牛的处理参数就可以了。https://developer.qiniu.com/dora/manual/3683/img-directions-for-use

**Comment by git-patrickliu** [comment]
@Dev-Wiki 嗯，是的 @Seifon 因为这个插件是基于七牛的，所以可以在url后面跟上七牛的处理参数就可以了。https://developer.qiniu.com/dora/manual/3683/img-directions-for-use
