### ISSUE TITLE
关于存储区域的问题

### ISSUE THREAD

**Issue by yischool611** [git-patrickliu/QINIU-save-online-images#9]
区域设置为华南，报错：{"error":"incorrect region"}
请问默认区域为什么值
是否可以设置存储区域

**Comment by git-patrickliu** [comment]
的确，我刚也试了一下 {"error":"incorrect region, please use up-z2.qiniup.com"}， 应该是之前的上传 API 只针对华东区的。我这几天看一下官方文档。

**Comment by git-patrickliu** [comment]
新增了一个存储区域。更新到最新的0.1.1版本就好了。
